2021-05-16 10:47:38 - INFO - creat an event and an object for Event class
NoneType: None
2021-05-16 10:48:50 - INFO - discount edited
NoneType: None
2021-05-16 10:49:11 - INFO - new discount category added to file discount
NoneType: None
2021-05-16 10:49:24 - INFO - discount edited
NoneType: None
2021-05-16 10:49:56 - INFO - discount edited
NoneType: None
2021-05-16 10:56:10 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:10 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:10 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:10 - INFO - discount edited
NoneType: None
2021-05-16 10:56:10 - INFO - discount edited
NoneType: None
2021-05-16 10:56:10 - INFO - discount edited
NoneType: None
2021-05-16 10:56:26 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:26 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:26 - ERROR - invalid input error
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 167, in edit_discount
    assert (id in list_index)
AssertionError
2021-05-16 10:56:26 - INFO - discount edited
NoneType: None
2021-05-16 10:56:26 - INFO - discount edited
NoneType: None
2021-05-16 10:56:26 - INFO - discount edited
NoneType: None
2021-05-16 10:58:02 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:58:02 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:58:02 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:58:02 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:59:09 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:59:09 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:59:09 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 10:59:09 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:00:35 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:00:35 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:00:35 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:00:35 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:14 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 299, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:18:43 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:18:51 - INFO - costumer exit
NoneType: None
2021-05-16 11:29:02 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 301, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:29:17 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:29:34 - INFO - costumer exit
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - tickets are sold successfully
NoneType: None
2021-05-16 11:31:13 - INFO - but ticket by costumer
NoneType: None
2021-05-16 11:31:21 - INFO - costumer exit
NoneType: None
2021-05-24 19:22:12 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 221, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 19:22:31 - INFO - tickets are sold successfully
NoneType: None
2021-05-24 19:29:59 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 221, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 19:29:59 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 221, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 19:30:30 - ERROR - Assertion error. the selected index is not exist
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 253, in buy_ticket
    id_2=int(input('Can you use discount based on your account type? if yes press the correspondance index: '))
ValueError: invalid literal for int() with base 10: 'student'
2021-05-24 19:30:30 - ERROR - Assertion error. the selected index is not exist
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 253, in buy_ticket
    id_2=int(input('Can you use discount based on your account type? if yes press the correspondance index: '))
ValueError: invalid literal for int() with base 10: 'student'
2021-05-24 19:30:30 - INFO - tickets are sold successfully
NoneType: None
2021-05-24 19:30:30 - INFO - tickets are sold successfully
NoneType: None
2021-05-24 19:36:28 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:36:28 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:36:28 - ERROR - assertion error by costumer, wrong input
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\main_menue.py", line 149, in <module>
    event.Event.display_event('file_event_csv')
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 302, in display_event
    my_logger_event.inf('evnt are displayed sucessfully', exc_info=True)
AttributeError: 'Logger' object has no attribute 'inf'
2021-05-24 19:36:39 - INFO - costumer exit
NoneType: None
2021-05-24 19:36:39 - INFO - costumer exit
NoneType: None
2021-05-24 19:36:39 - INFO - costumer exit
NoneType: None
2021-05-24 20:12:20 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 221, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 20:15:51 - ERROR - Assertion error. the selected index is not exist
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 253, in buy_ticket
    id_2=int(input('Can you use discount based on your account type? if yes press the correspondance index: '))
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 863, in raw_input
    password=False,
  File "C:\Users\1234\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 904, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2021-05-24 20:15:51 - INFO - tickets are sold successfully
NoneType: None
2021-05-24 20:19:47 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 221, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 20:19:55 - INFO - tickets are sold successfully
NoneType: None
2021-05-24 20:32:47 - ERROR - Assertion error. the left capacity is less than numbers of ticket
Traceback (most recent call last):
  File "D:\Maktab\week_7\final_project\New folder\event.py", line 222, in buy_ticket
    assert (ticket<int(event.left_capacity)) # you can add here checking time and date
AssertionError
2021-05-24 20:32:47 - INFO - tickets are sold successfully
NoneType: None
